### ISSUE TITLE
Getting rid of setInterval

### ISSUE THREAD

**Issue by simbleau** [Nul-led/bevy_web_keepalive#11]
I think most people who will use this plugin won't really know Web that well, and it may be confusing to someone "why should I use intervals instead of timeouts? What is that for?"

This question doesn't have an answer without knowing the implementation details of how bevy_web_keepalive functions.

My proposal is simple, but I wanted to ask for your opinion before submitting a PR:
- Remove the plugin setting to use Intervals
- Always use Timeouts
- Add the timeout Id as a parameter of the closure, so that it can be cleared when the world is dropped (no more JavaScript errors that continually print after a bevy panic due to a runaway timer)

The goal is just to make this plugin a little more simple. I'll be honest I think the plugin is very valuable but slightly over engineered and this would hopefully keep it more simple.

**Comment by Nul-led** [comment]
Sounds reasonable, although setInterval is technically better if we dont want to change the timeout very often because we save one v8 tick

**Comment by Nul-led** [comment]
Okay, thought a bit more about it; we can just .terminate() the worker once we drop the world. however we would need to store a ref of the worker in the world which might be complicated as web_sys objects usually dont work well with bevy storage.

**Comment by Nul-led** [comment]
decided against setTimeout in favor of setInterval to avoid issues with timer drift & wasted js engine ticks. this is optimal because in reality there is no reason why people would update the delay very often.
