### ISSUE TITLE
panic on non wasm target

### ISSUE THREAD

**Issue by mirsella** [Nul-led/bevy_web_keepalive#15]
hello !

Currently it panic
```
thread 'main' panicked at /home/mirsella/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-0.2.95/src/lib.rs:1021:1:
function not implemented on non-wasm32 targets
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at core/src/panicking.rs:223:5:
panic in a function that cannot unwind
```
at least having a compile_error on non wasm target, so that is doesn't compile instead of panicking at run time.
even better, would be to just do nothing if its not wasm

thanks

**Comment by Nul-led** [comment]
Since wasm bindgen compiles to native targets despite not supporting them i suppose this is the idiomatic way to do it.

**Comment by mirsella** [comment]
oh ok, thanks for the explanation, it seems weird but there must a be a good reason
