### ISSUE TITLE
Some fields are unclear footguns

### ISSUE THREAD

**Issue by simbleau** [Nul-led/bevy_web_keepalive#7]
Most of the fields of plugins are undocumented, while the plugins are documented.

For example, `scheduler_delay` is unclear that it is the interval by which to wake and run the schedule if the window is alt-tabbed. Maybe that's a special case of bad naming rather than bad documentation. Perhaps `wake_interval` would be better.

But also, why is `check_is_in_background` really a flag? 
The general flow should be: 
- If there is no window, it is headless! Always run on the interval.
- If there is a window, check if its hidden. Only run if it's hidden.
I'm actually not sure what purpose the flag has, as it only leaves room for people to erroneously use it.

**Comment by Nul-led** [comment]
ill rename scheduler_delay to wake_interval then
